name: my-ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
            postgresql db: page_analyzer
            postgresql user: ${{ secrets.NAME }}
            postgresql password: ${{ secrets.PASSWORD }}
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        # install poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make schema-load
          make check
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.SECRET_83 }}
        with:
          coverageCommand: make test-coverage
          debug: true
